-- Seed Daily Prompts for 2026
CREATE TABLE IF NOT EXISTS public.prompts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date DATE UNIQUE NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.prompts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read of prompts" ON public.prompts FOR SELECT USING (true);

INSERT INTO public.prompts (date, title, description) VALUES
('2026-01-01', 'The Snow Monster', 'Draw or build a monster that loves snowy mountains.'),
('2026-01-02', 'Space Explorer', 'Design a spaceship that travels to a planet made of candy.'),
('2026-01-03', 'Cardboard Castle', 'Build a fortress using only recycled materials from your house!'),
('2026-01-04', 'Color Explosion', 'Create a piece of art using every color in your crayon box.'),
('2026-01-05', 'Nature''s Face', 'Go outside and make a face using only leaves, twigs, and stones.'),
('2026-01-06', 'Dream Machine', 'Sketch a machine that can record your dreams while you sleep.'),
('2026-01-07', 'Invisible Friend', 'Paint a portrait of your favorite imaginary friend.'),
('2026-01-08', 'LEGO City', 'Build a tiny building for an ant to live in using LEGO bits.'),
('2026-01-09', 'Square World', 'Draw a landscape where everything—the trees, clouds, and sun—is a square!'),
('2026-01-10', 'Underwater Party', 'What do fish do at a birthday party? Show us with your art!'),
('2026-01-11', 'Robot Helper', 'Design a robot that can help you clean your room.'),
('2026-01-12', 'Magic Garden', 'Use markers to draw a garden where the flowers talk.'),
('2026-01-13', 'Dinosaur Picnic', 'Draw a T-Rex and a Triceratops sharing a giant sandwich.'),
('2026-01-14', 'Super Suit', 'If you were a superhero, what would your suit look like? Build it or draw it!'),
('2026-01-15', 'Flying Car', 'Design a car that has wings and flies through the clouds.'),
('2026-01-16', 'Miniature Food', 'Sculpt some tiny fruit or a tiny pizza out of playdough or clay.'),
('2026-01-17', 'Pattern Party', 'Fill a whole page with zig-zags, swirls, and polka dots!'),
('2026-01-18', 'Tree House', 'Design the ultimate tree house with a slide and a telescope.'),
('2026-01-19', 'Musical Monster', 'Draw a monster that plays five instruments at the same time!'),
('2026-01-20', 'Cloud Animals', 'Look at the sky (or imagine it) and draw animals made out of clouds.'),
('2026-01-21', 'Pet Dragon', 'What would your pet dragon look like? Is it fluffy or scaly?'),
('2026-01-22', 'Floating Island', 'Draw an island floating in the air with a waterfall.'),
('2026-01-23', 'Fruit Robot', 'Design a robot made entirely out of fruit (an apple head, banana arms!)'),
('2026-01-24', 'Shadow Art', 'Trace the shadow of a toy on a piece of paper and turn it into something new.'),
('2026-01-25', 'Rainbow Bridge', 'Paint a bridge made of rainbows connecting two mountains.'),
('2026-01-26', 'Starlight City', 'Draw a city that only exists at night and is lit by stars.'),
('2026-01-27', 'Alphabet Animal', 'Pick a letter and draw an animal that starts with that letter using the letter''s shape.'),
('2026-01-28', 'Time Machine', 'If you could visit the past or future, what would your time machine look like?'),
('2026-01-29', 'Cookie Planet', 'Design a planet that is one giant chocolate chip cookie.'),
('2026-01-30', 'Water Monster', 'Draw a monster that lives at the bottom of a swimming pool.'),
('2026-01-31', 'The Snow Monster', 'Draw or build a monster that loves snowy mountains.'),
('2026-02-01', 'Space Explorer', 'Design a spaceship that travels to a planet made of candy.'),
('2026-02-02', 'Cardboard Castle', 'Build a fortress using only recycled materials from your house!'),
('2026-02-03', 'Color Explosion', 'Create a piece of art using every color in your crayon box.'),
('2026-02-04', 'Nature''s Face', 'Go outside and make a face using only leaves, twigs, and stones.'),
('2026-02-05', 'Dream Machine', 'Sketch a machine that can record your dreams while you sleep.'),
('2026-02-06', 'Invisible Friend', 'Paint a portrait of your favorite imaginary friend.'),
('2026-02-07', 'LEGO City', 'Build a tiny building for an ant to live in using LEGO bits.'),
('2026-02-08', 'Square World', 'Draw a landscape where everything—the trees, clouds, and sun—is a square!'),
('2026-02-09', 'Underwater Party', 'What do fish do at a birthday party? Show us with your art!'),
('2026-02-10', 'Robot Helper', 'Design a robot that can help you clean your room.'),
('2026-02-11', 'Magic Garden', 'Use markers to draw a garden where the flowers talk.'),
('2026-02-12', 'Dinosaur Picnic', 'Draw a T-Rex and a Triceratops sharing a giant sandwich.'),
('2026-02-13', 'Super Suit', 'If you were a superhero, what would your suit look like? Build it or draw it!'),
('2026-02-14', 'Flying Car', 'Design a car that has wings and flies through the clouds.'),
('2026-02-15', 'Miniature Food', 'Sculpt some tiny fruit or a tiny pizza out of playdough or clay.'),
('2026-02-16', 'Pattern Party', 'Fill a whole page with zig-zags, swirls, and polka dots!'),
('2026-02-17', 'Tree House', 'Design the ultimate tree house with a slide and a telescope.'),
('2026-02-18', 'Musical Monster', 'Draw a monster that plays five instruments at the same time!'),
('2026-02-19', 'Cloud Animals', 'Look at the sky (or imagine it) and draw animals made out of clouds.'),
('2026-02-20', 'Pet Dragon', 'What would your pet dragon look like? Is it fluffy or scaly?'),
('2026-02-21', 'Floating Island', 'Draw an island floating in the air with a waterfall.'),
('2026-02-22', 'Fruit Robot', 'Design a robot made entirely out of fruit (an apple head, banana arms!)'),
('2026-02-23', 'Shadow Art', 'Trace the shadow of a toy on a piece of paper and turn it into something new.'),
('2026-02-24', 'Rainbow Bridge', 'Paint a bridge made of rainbows connecting two mountains.'),
('2026-02-25', 'Starlight City', 'Draw a city that only exists at night and is lit by stars.'),
('2026-02-26', 'Alphabet Animal', 'Pick a letter and draw an animal that starts with that letter using the letter''s shape.'),
('2026-02-27', 'Time Machine', 'If you could visit the past or future, what would your time machine look like?'),
('2026-02-28', 'Cookie Planet', 'Design a planet that is one giant chocolate chip cookie.'),
('2026-03-01', 'Water Monster', 'Draw a monster that lives at the bottom of a swimming pool.'),
('2026-03-02', 'The Snow Monster', 'Draw or build a monster that loves snowy mountains.'),
('2026-03-03', 'Space Explorer', 'Design a spaceship that travels to a planet made of candy.'),
('2026-03-04', 'Cardboard Castle', 'Build a fortress using only recycled materials from your house!'),
('2026-03-05', 'Color Explosion', 'Create a piece of art using every color in your crayon box.'),
('2026-03-06', 'Nature''s Face', 'Go outside and make a face using only leaves, twigs, and stones.'),
('2026-03-07', 'Dream Machine', 'Sketch a machine that can record your dreams while you sleep.'),
('2026-03-08', 'Invisible Friend', 'Paint a portrait of your favorite imaginary friend.'),
('2026-03-09', 'LEGO City', 'Build a tiny building for an ant to live in using LEGO bits.'),
('2026-03-10', 'Square World', 'Draw a landscape where everything—the trees, clouds, and sun—is a square!'),
('2026-03-11', 'Underwater Party', 'What do fish do at a birthday party? Show us with your art!'),
('2026-03-12', 'Robot Helper', 'Design a robot that can help you clean your room.'),
('2026-03-13', 'Magic Garden', 'Use markers to draw a garden where the flowers talk.'),
('2026-03-14', 'Dinosaur Picnic', 'Draw a T-Rex and a Triceratops sharing a giant sandwich.'),
('2026-03-15', 'Super Suit', 'If you were a superhero, what would your suit look like? Build it or draw it!'),
('2026-03-16', 'Flying Car', 'Design a car that has wings and flies through the clouds.'),
('2026-03-17', 'Miniature Food', 'Sculpt some tiny fruit or a tiny pizza out of playdough or clay.'),
('2026-03-18', 'Pattern Party', 'Fill a whole page with zig-zags, swirls, and polka dots!'),
('2026-03-19', 'Tree House', 'Design the ultimate tree house with a slide and a telescope.'),
('2026-03-20', 'Musical Monster', 'Draw a monster that plays five instruments at the same time!'),
('2026-03-21', 'Cloud Animals', 'Look at the sky (or imagine it) and draw animals made out of clouds.'),
('2026-03-22', 'Pet Dragon', 'What would your pet dragon look like? Is it fluffy or scaly?'),
('2026-03-23', 'Floating Island', 'Draw an island floating in the air with a waterfall.'),
('2026-03-24', 'Fruit Robot', 'Design a robot made entirely out of fruit (an apple head, banana arms!)'),
('2026-03-25', 'Shadow Art', 'Trace the shadow of a toy on a piece of paper and turn it into something new.'),
('2026-03-26', 'Rainbow Bridge', 'Paint a bridge made of rainbows connecting two mountains.'),
('2026-03-27', 'Starlight City', 'Draw a city that only exists at night and is lit by stars.'),
('2026-03-28', 'Alphabet Animal', 'Pick a letter and draw an animal that starts with that letter using the letter''s shape.'),
('2026-03-29', 'Time Machine', 'If you could visit the past or future, what would your time machine look like?'),
('2026-03-30', 'Cookie Planet', 'Design a planet that is one giant chocolate chip cookie.'),
('2026-03-31', 'Water Monster', 'Draw a monster that lives at the bottom of a swimming pool.'),
('2026-04-01', 'The Snow Monster', 'Draw or build a monster that loves snowy mountains.'),
('2026-04-02', 'Space Explorer', 'Design a spaceship that travels to a planet made of candy.'),
('2026-04-03', 'Cardboard Castle', 'Build a fortress using only recycled materials from your house!'),
('2026-04-04', 'Color Explosion', 'Create a piece of art using every color in your crayon box.'),
('2026-04-05', 'Nature''s Face', 'Go outside and make a face using only leaves, twigs, and stones.'),
('2026-04-06', 'Dream Machine', 'Sketch a machine that can record your dreams while you sleep.'),
('2026-04-07', 'Invisible Friend', 'Paint a portrait of your favorite imaginary friend.'),
('2026-04-08', 'LEGO City', 'Build a tiny building for an ant to live in using LEGO bits.'),
('2026-04-09', 'Square World', 'Draw a landscape where everything—the trees, clouds, and sun—is a square!'),
('2026-04-10', 'Underwater Party', 'What do fish do at a birthday party? Show us with your art!'),
('2026-04-11', 'Robot Helper', 'Design a robot that can help you clean your room.'),
('2026-04-12', 'Magic Garden', 'Use markers to draw a garden where the flowers talk.'),
('2026-04-13', 'Dinosaur Picnic', 'Draw a T-Rex and a Triceratops sharing a giant sandwich.'),
('2026-04-14', 'Super Suit', 'If you were a superhero, what would your suit look like? Build it or draw it!'),
('2026-04-15', 'Flying Car', 'Design a car that has wings and flies through the clouds.'),
('2026-04-16', 'Miniature Food', 'Sculpt some tiny fruit or a tiny pizza out of playdough or clay.'),
('2026-04-17', 'Pattern Party', 'Fill a whole page with zig-zags, swirls, and polka dots!'),
('2026-04-18', 'Tree House', 'Design the ultimate tree house with a slide and a telescope.'),
('2026-04-19', 'Musical Monster', 'Draw a monster that plays five instruments at the same time!'),
('2026-04-20', 'Cloud Animals', 'Look at the sky (or imagine it) and draw animals made out of clouds.'),
('2026-04-21', 'Pet Dragon', 'What would your pet dragon look like? Is it fluffy or scaly?'),
('2026-04-22', 'Floating Island', 'Draw an island floating in the air with a waterfall.'),
('2026-04-23', 'Fruit Robot', 'Design a robot made entirely out of fruit (an apple head, banana arms!)'),
('2026-04-24', 'Shadow Art', 'Trace the shadow of a toy on a piece of paper and turn it into something new.'),
('2026-04-25', 'Rainbow Bridge', 'Paint a bridge made of rainbows connecting two mountains.'),
('2026-04-26', 'Starlight City', 'Draw a city that only exists at night and is lit by stars.'),
('2026-04-27', 'Alphabet Animal', 'Pick a letter and draw an animal that starts with that letter using the letter''s shape.'),
('2026-04-28', 'Time Machine', 'If you could visit the past or future, what would your time machine look like?'),
('2026-04-29', 'Cookie Planet', 'Design a planet that is one giant chocolate chip cookie.'),
('2026-04-30', 'Water Monster', 'Draw a monster that lives at the bottom of a swimming pool.'),
('2026-05-01', 'The Snow Monster', 'Draw or build a monster that loves snowy mountains.'),
('2026-05-02', 'Space Explorer', 'Design a spaceship that travels to a planet made of candy.'),
('2026-05-03', 'Cardboard Castle', 'Build a fortress using only recycled materials from your house!'),
('2026-05-04', 'Color Explosion', 'Create a piece of art using every color in your crayon box.'),
('2026-05-05', 'Nature''s Face', 'Go outside and make a face using only leaves, twigs, and stones.'),
('2026-05-06', 'Dream Machine', 'Sketch a machine that can record your dreams while you sleep.'),
('2026-05-07', 'Invisible Friend', 'Paint a portrait of your favorite imaginary friend.'),
('2026-05-08', 'LEGO City', 'Build a tiny building for an ant to live in using LEGO bits.'),
('2026-05-09', 'Square World', 'Draw a landscape where everything—the trees, clouds, and sun—is a square!'),
('2026-05-10', 'Underwater Party', 'What do fish do at a birthday party? Show us with your art!'),
('2026-05-11', 'Robot Helper', 'Design a robot that can help you clean your room.'),
('2026-05-12', 'Magic Garden', 'Use markers to draw a garden where the flowers talk.'),
('2026-05-13', 'Dinosaur Picnic', 'Draw a T-Rex and a Triceratops sharing a giant sandwich.'),
('2026-05-14', 'Super Suit', 'If you were a superhero, what would your suit look like? Build it or draw it!'),
('2026-05-15', 'Flying Car', 'Design a car that has wings and flies through the clouds.'),
('2026-05-16', 'Miniature Food', 'Sculpt some tiny fruit or a tiny pizza out of playdough or clay.'),
('2026-05-17', 'Pattern Party', 'Fill a whole page with zig-zags, swirls, and polka dots!'),
('2026-05-18', 'Tree House', 'Design the ultimate tree house with a slide and a telescope.'),
('2026-05-19', 'Musical Monster', 'Draw a monster that plays five instruments at the same time!'),
('2026-05-20', 'Cloud Animals', 'Look at the sky (or imagine it) and draw animals made out of clouds.'),
('2026-05-21', 'Pet Dragon', 'What would your pet dragon look like? Is it fluffy or scaly?'),
('2026-05-22', 'Floating Island', 'Draw an island floating in the air with a waterfall.'),
('2026-05-23', 'Fruit Robot', 'Design a robot made entirely out of fruit (an apple head, banana arms!)'),
('2026-05-24', 'Shadow Art', 'Trace the shadow of a toy on a piece of paper and turn it into something new.'),
('2026-05-25', 'Rainbow Bridge', 'Paint a bridge made of rainbows connecting two mountains.'),
('2026-05-26', 'Starlight City', 'Draw a city that only exists at night and is lit by stars.'),
('2026-05-27', 'Alphabet Animal', 'Pick a letter and draw an animal that starts with that letter using the letter''s shape.'),
('2026-05-28', 'Time Machine', 'If you could visit the past or future, what would your time machine look like?'),
('2026-05-29', 'Cookie Planet', 'Design a planet that is one giant chocolate chip cookie.'),
('2026-05-30', 'Water Monster', 'Draw a monster that lives at the bottom of a swimming pool.'),
('2026-05-31', 'The Snow Monster', 'Draw or build a monster that loves snowy mountains.'),
('2026-06-01', 'Space Explorer', 'Design a spaceship that travels to a planet made of candy.'),
('2026-06-02', 'Cardboard Castle', 'Build a fortress using only recycled materials from your house!'),
('2026-06-03', 'Color Explosion', 'Create a piece of art using every color in your crayon box.'),
('2026-06-04', 'Nature''s Face', 'Go outside and make a face using only leaves, twigs, and stones.'),
('2026-06-05', 'Dream Machine', 'Sketch a machine that can record your dreams while you sleep.'),
('2026-06-06', 'Invisible Friend', 'Paint a portrait of your favorite imaginary friend.'),
('2026-06-07', 'LEGO City', 'Build a tiny building for an ant to live in using LEGO bits.'),
('2026-06-08', 'Square World', 'Draw a landscape where everything—the trees, clouds, and sun—is a square!'),
('2026-06-09', 'Underwater Party', 'What do fish do at a birthday party? Show us with your art!'),
('2026-06-10', 'Robot Helper', 'Design a robot that can help you clean your room.'),
('2026-06-11', 'Magic Garden', 'Use markers to draw a garden where the flowers talk.'),
('2026-06-12', 'Dinosaur Picnic', 'Draw a T-Rex and a Triceratops sharing a giant sandwich.'),
('2026-06-13', 'Super Suit', 'If you were a superhero, what would your suit look like? Build it or draw it!'),
('2026-06-14', 'Flying Car', 'Design a car that has wings and flies through the clouds.'),
('2026-06-15', 'Miniature Food', 'Sculpt some tiny fruit or a tiny pizza out of playdough or clay.'),
('2026-06-16', 'Pattern Party', 'Fill a whole page with zig-zags, swirls, and polka dots!'),
('2026-06-17', 'Tree House', 'Design the ultimate tree house with a slide and a telescope.'),
('2026-06-18', 'Musical Monster', 'Draw a monster that plays five instruments at the same time!'),
('2026-06-19', 'Cloud Animals', 'Look at the sky (or imagine it) and draw animals made out of clouds.'),
('2026-06-20', 'Pet Dragon', 'What would your pet dragon look like? Is it fluffy or scaly?'),
('2026-06-21', 'Floating Island', 'Draw an island floating in the air with a waterfall.'),
('2026-06-22', 'Fruit Robot', 'Design a robot made entirely out of fruit (an apple head, banana arms!)'),
('2026-06-23', 'Shadow Art', 'Trace the shadow of a toy on a piece of paper and turn it into something new.'),
('2026-06-24', 'Rainbow Bridge', 'Paint a bridge made of rainbows connecting two mountains.'),
('2026-06-25', 'Starlight City', 'Draw a city that only exists at night and is lit by stars.'),
('2026-06-26', 'Alphabet Animal', 'Pick a letter and draw an animal that starts with that letter using the letter''s shape.'),
('2026-06-27', 'Time Machine', 'If you could visit the past or future, what would your time machine look like?'),
('2026-06-28', 'Cookie Planet', 'Design a planet that is one giant chocolate chip cookie.'),
('2026-06-29', 'Water Monster', 'Draw a monster that lives at the bottom of a swimming pool.'),
('2026-06-30', 'The Snow Monster', 'Draw or build a monster that loves snowy mountains.'),
('2026-07-01', 'Space Explorer', 'Design a spaceship that travels to a planet made of candy.'),
('2026-07-02', 'Cardboard Castle', 'Build a fortress using only recycled materials from your house!'),
('2026-07-03', 'Color Explosion', 'Create a piece of art using every color in your crayon box.'),
('2026-07-04', 'Nature''s Face', 'Go outside and make a face using only leaves, twigs, and stones.'),
('2026-07-05', 'Dream Machine', 'Sketch a machine that can record your dreams while you sleep.'),
('2026-07-06', 'Invisible Friend', 'Paint a portrait of your favorite imaginary friend.'),
('2026-07-07', 'LEGO City', 'Build a tiny building for an ant to live in using LEGO bits.'),
('2026-07-08', 'Square World', 'Draw a landscape where everything—the trees, clouds, and sun—is a square!'),
('2026-07-09', 'Underwater Party', 'What do fish do at a birthday party? Show us with your art!'),
('2026-07-10', 'Robot Helper', 'Design a robot that can help you clean your room.'),
('2026-07-11', 'Magic Garden', 'Use markers to draw a garden where the flowers talk.'),
('2026-07-12', 'Dinosaur Picnic', 'Draw a T-Rex and a Triceratops sharing a giant sandwich.'),
('2026-07-13', 'Super Suit', 'If you were a superhero, what would your suit look like? Build it or draw it!'),
('2026-07-14', 'Flying Car', 'Design a car that has wings and flies through the clouds.'),
('2026-07-15', 'Miniature Food', 'Sculpt some tiny fruit or a tiny pizza out of playdough or clay.'),
('2026-07-16', 'Pattern Party', 'Fill a whole page with zig-zags, swirls, and polka dots!'),
('2026-07-17', 'Tree House', 'Design the ultimate tree house with a slide and a telescope.'),
('2026-07-18', 'Musical Monster', 'Draw a monster that plays five instruments at the same time!'),
('2026-07-19', 'Cloud Animals', 'Look at the sky (or imagine it) and draw animals made out of clouds.'),
('2026-07-20', 'Pet Dragon', 'What would your pet dragon look like? Is it fluffy or scaly?'),
('2026-07-21', 'Floating Island', 'Draw an island floating in the air with a waterfall.'),
('2026-07-22', 'Fruit Robot', 'Design a robot made entirely out of fruit (an apple head, banana arms!)'),
('2026-07-23', 'Shadow Art', 'Trace the shadow of a toy on a piece of paper and turn it into something new.'),
('2026-07-24', 'Rainbow Bridge', 'Paint a bridge made of rainbows connecting two mountains.'),
('2026-07-25', 'Starlight City', 'Draw a city that only exists at night and is lit by stars.'),
('2026-07-26', 'Alphabet Animal', 'Pick a letter and draw an animal that starts with that letter using the letter''s shape.'),
('2026-07-27', 'Time Machine', 'If you could visit the past or future, what would your time machine look like?'),
('2026-07-28', 'Cookie Planet', 'Design a planet that is one giant chocolate chip cookie.'),
('2026-07-29', 'Water Monster', 'Draw a monster that lives at the bottom of a swimming pool.'),
('2026-07-30', 'The Snow Monster', 'Draw or build a monster that loves snowy mountains.'),
('2026-07-31', 'Space Explorer', 'Design a spaceship that travels to a planet made of candy.'),
('2026-08-01', 'Cardboard Castle', 'Build a fortress using only recycled materials from your house!'),
('2026-08-02', 'Color Explosion', 'Create a piece of art using every color in your crayon box.'),
('2026-08-03', 'Nature''s Face', 'Go outside and make a face using only leaves, twigs, and stones.'),
('2026-08-04', 'Dream Machine', 'Sketch a machine that can record your dreams while you sleep.'),
('2026-08-05', 'Invisible Friend', 'Paint a portrait of your favorite imaginary friend.'),
('2026-08-06', 'LEGO City', 'Build a tiny building for an ant to live in using LEGO bits.'),
('2026-08-07', 'Square World', 'Draw a landscape where everything—the trees, clouds, and sun—is a square!'),
('2026-08-08', 'Underwater Party', 'What do fish do at a birthday party? Show us with your art!'),
('2026-08-09', 'Robot Helper', 'Design a robot that can help you clean your room.'),
('2026-08-10', 'Magic Garden', 'Use markers to draw a garden where the flowers talk.'),
('2026-08-11', 'Dinosaur Picnic', 'Draw a T-Rex and a Triceratops sharing a giant sandwich.'),
('2026-08-12', 'Super Suit', 'If you were a superhero, what would your suit look like? Build it or draw it!'),
('2026-08-13', 'Flying Car', 'Design a car that has wings and flies through the clouds.'),
('2026-08-14', 'Miniature Food', 'Sculpt some tiny fruit or a tiny pizza out of playdough or clay.'),
('2026-08-15', 'Pattern Party', 'Fill a whole page with zig-zags, swirls, and polka dots!'),
('2026-08-16', 'Tree House', 'Design the ultimate tree house with a slide and a telescope.'),
('2026-08-17', 'Musical Monster', 'Draw a monster that plays five instruments at the same time!'),
('2026-08-18', 'Cloud Animals', 'Look at the sky (or imagine it) and draw animals made out of clouds.'),
('2026-08-19', 'Pet Dragon', 'What would your pet dragon look like? Is it fluffy or scaly?'),
('2026-08-20', 'Floating Island', 'Draw an island floating in the air with a waterfall.'),
('2026-08-21', 'Fruit Robot', 'Design a robot made entirely out of fruit (an apple head, banana arms!)'),
('2026-08-22', 'Shadow Art', 'Trace the shadow of a toy on a piece of paper and turn it into something new.'),
('2026-08-23', 'Rainbow Bridge', 'Paint a bridge made of rainbows connecting two mountains.'),
('2026-08-24', 'Starlight City', 'Draw a city that only exists at night and is lit by stars.'),
('2026-08-25', 'Alphabet Animal', 'Pick a letter and draw an animal that starts with that letter using the letter''s shape.'),
('2026-08-26', 'Time Machine', 'If you could visit the past or future, what would your time machine look like?'),
('2026-08-27', 'Cookie Planet', 'Design a planet that is one giant chocolate chip cookie.'),
('2026-08-28', 'Water Monster', 'Draw a monster that lives at the bottom of a swimming pool.'),
('2026-08-29', 'The Snow Monster', 'Draw or build a monster that loves snowy mountains.'),
('2026-08-30', 'Space Explorer', 'Design a spaceship that travels to a planet made of candy.'),
('2026-08-31', 'Cardboard Castle', 'Build a fortress using only recycled materials from your house!'),
('2026-09-01', 'Color Explosion', 'Create a piece of art using every color in your crayon box.'),
('2026-09-02', 'Nature''s Face', 'Go outside and make a face using only leaves, twigs, and stones.'),
('2026-09-03', 'Dream Machine', 'Sketch a machine that can record your dreams while you sleep.'),
('2026-09-04', 'Invisible Friend', 'Paint a portrait of your favorite imaginary friend.'),
('2026-09-05', 'LEGO City', 'Build a tiny building for an ant to live in using LEGO bits.'),
('2026-09-06', 'Square World', 'Draw a landscape where everything—the trees, clouds, and sun—is a square!'),
('2026-09-07', 'Underwater Party', 'What do fish do at a birthday party? Show us with your art!'),
('2026-09-08', 'Robot Helper', 'Design a robot that can help you clean your room.'),
('2026-09-09', 'Magic Garden', 'Use markers to draw a garden where the flowers talk.'),
('2026-09-10', 'Dinosaur Picnic', 'Draw a T-Rex and a Triceratops sharing a giant sandwich.'),
('2026-09-11', 'Super Suit', 'If you were a superhero, what would your suit look like? Build it or draw it!'),
('2026-09-12', 'Flying Car', 'Design a car that has wings and flies through the clouds.'),
('2026-09-13', 'Miniature Food', 'Sculpt some tiny fruit or a tiny pizza out of playdough or clay.'),
('2026-09-14', 'Pattern Party', 'Fill a whole page with zig-zags, swirls, and polka dots!'),
('2026-09-15', 'Tree House', 'Design the ultimate tree house with a slide and a telescope.'),
('2026-09-16', 'Musical Monster', 'Draw a monster that plays five instruments at the same time!'),
('2026-09-17', 'Cloud Animals', 'Look at the sky (or imagine it) and draw animals made out of clouds.'),
('2026-09-18', 'Pet Dragon', 'What would your pet dragon look like? Is it fluffy or scaly?'),
('2026-09-19', 'Floating Island', 'Draw an island floating in the air with a waterfall.'),
('2026-09-20', 'Fruit Robot', 'Design a robot made entirely out of fruit (an apple head, banana arms!)'),
('2026-09-21', 'Shadow Art', 'Trace the shadow of a toy on a piece of paper and turn it into something new.'),
('2026-09-22', 'Rainbow Bridge', 'Paint a bridge made of rainbows connecting two mountains.'),
('2026-09-23', 'Starlight City', 'Draw a city that only exists at night and is lit by stars.'),
('2026-09-24', 'Alphabet Animal', 'Pick a letter and draw an animal that starts with that letter using the letter''s shape.'),
('2026-09-25', 'Time Machine', 'If you could visit the past or future, what would your time machine look like?'),
('2026-09-26', 'Cookie Planet', 'Design a planet that is one giant chocolate chip cookie.'),
('2026-09-27', 'Water Monster', 'Draw a monster that lives at the bottom of a swimming pool.'),
('2026-09-28', 'The Snow Monster', 'Draw or build a monster that loves snowy mountains.'),
('2026-09-29', 'Space Explorer', 'Design a spaceship that travels to a planet made of candy.'),
('2026-09-30', 'Cardboard Castle', 'Build a fortress using only recycled materials from your house!'),
('2026-10-01', 'Color Explosion', 'Create a piece of art using every color in your crayon box.'),
('2026-10-02', 'Nature''s Face', 'Go outside and make a face using only leaves, twigs, and stones.'),
('2026-10-03', 'Dream Machine', 'Sketch a machine that can record your dreams while you sleep.'),
('2026-10-04', 'Invisible Friend', 'Paint a portrait of your favorite imaginary friend.'),
('2026-10-05', 'LEGO City', 'Build a tiny building for an ant to live in using LEGO bits.'),
('2026-10-06', 'Square World', 'Draw a landscape where everything—the trees, clouds, and sun—is a square!'),
('2026-10-07', 'Underwater Party', 'What do fish do at a birthday party? Show us with your art!'),
('2026-10-08', 'Robot Helper', 'Design a robot that can help you clean your room.'),
('2026-10-09', 'Magic Garden', 'Use markers to draw a garden where the flowers talk.'),
('2026-10-10', 'Dinosaur Picnic', 'Draw a T-Rex and a Triceratops sharing a giant sandwich.'),
('2026-10-11', 'Super Suit', 'If you were a superhero, what would your suit look like? Build it or draw it!'),
('2026-10-12', 'Flying Car', 'Design a car that has wings and flies through the clouds.'),
('2026-10-13', 'Miniature Food', 'Sculpt some tiny fruit or a tiny pizza out of playdough or clay.'),
('2026-10-14', 'Pattern Party', 'Fill a whole page with zig-zags, swirls, and polka dots!'),
('2026-10-15', 'Tree House', 'Design the ultimate tree house with a slide and a telescope.'),
('2026-10-16', 'Musical Monster', 'Draw a monster that plays five instruments at the same time!'),
('2026-10-17', 'Cloud Animals', 'Look at the sky (or imagine it) and draw animals made out of clouds.'),
('2026-10-18', 'Pet Dragon', 'What would your pet dragon look like? Is it fluffy or scaly?'),
('2026-10-19', 'Floating Island', 'Draw an island floating in the air with a waterfall.'),
('2026-10-20', 'Fruit Robot', 'Design a robot made entirely out of fruit (an apple head, banana arms!)'),
('2026-10-21', 'Shadow Art', 'Trace the shadow of a toy on a piece of paper and turn it into something new.'),
('2026-10-22', 'Rainbow Bridge', 'Paint a bridge made of rainbows connecting two mountains.'),
('2026-10-23', 'Starlight City', 'Draw a city that only exists at night and is lit by stars.'),
('2026-10-24', 'Alphabet Animal', 'Pick a letter and draw an animal that starts with that letter using the letter''s shape.'),
('2026-10-25', 'Time Machine', 'If you could visit the past or future, what would your time machine look like?'),
('2026-10-26', 'Cookie Planet', 'Design a planet that is one giant chocolate chip cookie.'),
('2026-10-27', 'Water Monster', 'Draw a monster that lives at the bottom of a swimming pool.'),
('2026-10-28', 'The Snow Monster', 'Draw or build a monster that loves snowy mountains.'),
('2026-10-29', 'Space Explorer', 'Design a spaceship that travels to a planet made of candy.'),
('2026-10-30', 'Cardboard Castle', 'Build a fortress using only recycled materials from your house!'),
('2026-10-31', 'Color Explosion', 'Create a piece of art using every color in your crayon box.'),
('2026-11-01', 'Nature''s Face', 'Go outside and make a face using only leaves, twigs, and stones.'),
('2026-11-02', 'Dream Machine', 'Sketch a machine that can record your dreams while you sleep.'),
('2026-11-03', 'Invisible Friend', 'Paint a portrait of your favorite imaginary friend.'),
('2026-11-04', 'LEGO City', 'Build a tiny building for an ant to live in using LEGO bits.'),
('2026-11-05', 'Square World', 'Draw a landscape where everything—the trees, clouds, and sun—is a square!'),
('2026-11-06', 'Underwater Party', 'What do fish do at a birthday party? Show us with your art!'),
('2026-11-07', 'Robot Helper', 'Design a robot that can help you clean your room.'),
('2026-11-08', 'Magic Garden', 'Use markers to draw a garden where the flowers talk.'),
('2026-11-09', 'Dinosaur Picnic', 'Draw a T-Rex and a Triceratops sharing a giant sandwich.'),
('2026-11-10', 'Super Suit', 'If you were a superhero, what would your suit look like? Build it or draw it!'),
('2026-11-11', 'Flying Car', 'Design a car that has wings and flies through the clouds.'),
('2026-11-12', 'Miniature Food', 'Sculpt some tiny fruit or a tiny pizza out of playdough or clay.'),
('2026-11-13', 'Pattern Party', 'Fill a whole page with zig-zags, swirls, and polka dots!'),
('2026-11-14', 'Tree House', 'Design the ultimate tree house with a slide and a telescope.'),
('2026-11-15', 'Musical Monster', 'Draw a monster that plays five instruments at the same time!'),
('2026-11-16', 'Cloud Animals', 'Look at the sky (or imagine it) and draw animals made out of clouds.'),
('2026-11-17', 'Pet Dragon', 'What would your pet dragon look like? Is it fluffy or scaly?'),
('2026-11-18', 'Floating Island', 'Draw an island floating in the air with a waterfall.'),
('2026-11-19', 'Fruit Robot', 'Design a robot made entirely out of fruit (an apple head, banana arms!)'),
('2026-11-20', 'Shadow Art', 'Trace the shadow of a toy on a piece of paper and turn it into something new.'),
('2026-11-21', 'Rainbow Bridge', 'Paint a bridge made of rainbows connecting two mountains.'),
('2026-11-22', 'Starlight City', 'Draw a city that only exists at night and is lit by stars.'),
('2026-11-23', 'Alphabet Animal', 'Pick a letter and draw an animal that starts with that letter using the letter''s shape.'),
('2026-11-24', 'Time Machine', 'If you could visit the past or future, what would your time machine look like?'),
('2026-11-25', 'Cookie Planet', 'Design a planet that is one giant chocolate chip cookie.'),
('2026-11-26', 'Water Monster', 'Draw a monster that lives at the bottom of a swimming pool.'),
('2026-11-27', 'The Snow Monster', 'Draw or build a monster that loves snowy mountains.'),
('2026-11-28', 'Space Explorer', 'Design a spaceship that travels to a planet made of candy.'),
('2026-11-29', 'Cardboard Castle', 'Build a fortress using only recycled materials from your house!'),
('2026-11-30', 'Color Explosion', 'Create a piece of art using every color in your crayon box.'),
('2026-12-01', 'Nature''s Face', 'Go outside and make a face using only leaves, twigs, and stones.'),
('2026-12-02', 'Dream Machine', 'Sketch a machine that can record your dreams while you sleep.'),
('2026-12-03', 'Invisible Friend', 'Paint a portrait of your favorite imaginary friend.'),
('2026-12-04', 'LEGO City', 'Build a tiny building for an ant to live in using LEGO bits.'),
('2026-12-05', 'Square World', 'Draw a landscape where everything—the trees, clouds, and sun—is a square!'),
('2026-12-06', 'Underwater Party', 'What do fish do at a birthday party? Show us with your art!'),
('2026-12-07', 'Robot Helper', 'Design a robot that can help you clean your room.'),
('2026-12-08', 'Magic Garden', 'Use markers to draw a garden where the flowers talk.'),
('2026-12-09', 'Dinosaur Picnic', 'Draw a T-Rex and a Triceratops sharing a giant sandwich.'),
('2026-12-10', 'Super Suit', 'If you were a superhero, what would your suit look like? Build it or draw it!'),
('2026-12-11', 'Flying Car', 'Design a car that has wings and flies through the clouds.'),
('2026-12-12', 'Miniature Food', 'Sculpt some tiny fruit or a tiny pizza out of playdough or clay.'),
('2026-12-13', 'Pattern Party', 'Fill a whole page with zig-zags, swirls, and polka dots!'),
('2026-12-14', 'Tree House', 'Design the ultimate tree house with a slide and a telescope.'),
('2026-12-15', 'Musical Monster', 'Draw a monster that plays five instruments at the same time!'),
('2026-12-16', 'Cloud Animals', 'Look at the sky (or imagine it) and draw animals made out of clouds.'),
('2026-12-17', 'Pet Dragon', 'What would your pet dragon look like? Is it fluffy or scaly?'),
('2026-12-18', 'Floating Island', 'Draw an island floating in the air with a waterfall.'),
('2026-12-19', 'Fruit Robot', 'Design a robot made entirely out of fruit (an apple head, banana arms!)'),
('2026-12-20', 'Shadow Art', 'Trace the shadow of a toy on a piece of paper and turn it into something new.'),
('2026-12-21', 'Rainbow Bridge', 'Paint a bridge made of rainbows connecting two mountains.'),
('2026-12-22', 'Starlight City', 'Draw a city that only exists at night and is lit by stars.'),
('2026-12-23', 'Alphabet Animal', 'Pick a letter and draw an animal that starts with that letter using the letter''s shape.'),
('2026-12-24', 'Time Machine', 'If you could visit the past or future, what would your time machine look like?'),
('2026-12-25', 'Cookie Planet', 'Design a planet that is one giant chocolate chip cookie.'),
('2026-12-26', 'Water Monster', 'Draw a monster that lives at the bottom of a swimming pool.'),
('2026-12-27', 'The Snow Monster', 'Draw or build a monster that loves snowy mountains.'),
('2026-12-28', 'Space Explorer', 'Design a spaceship that travels to a planet made of candy.'),
('2026-12-29', 'Cardboard Castle', 'Build a fortress using only recycled materials from your house!'),
('2026-12-30', 'Color Explosion', 'Create a piece of art using every color in your crayon box.'),
('2026-12-31', 'Nature''s Face', 'Go outside and make a face using only leaves, twigs, and stones.') ON CONFLICT (date) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description;